export const ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
  RECOVER_PASSWORD_REQUEST: 'RECOVER_PASSWORD_REQUEST',
  RECOVER_PASSWORD_SUCCESS: 'RECOVER_PASSWORD_SUCCESS',
  RECOVER_PASSWORD_FAILURE: 'RECOVER_PASSWORD_FAILURE',
  PASSWORD_UPDATE_REQUEST: 'PASSWORD_UPDATE_REQUEST',
  PASSWORD_UPDATE_SUCCESS: 'PASSWORD_UPDATE_SUCCESS',
  PASSWORD_UPDATE_FAILURE: 'PASSWORD_UPDATE_FAILURE',
  CONFIRM_OTP_REQUEST: 'CONFIRM_OTP_REQUEST',
  CONFIRM_OTP_SUCCESS: 'CONFIRM_OTP_SUCCESS',
  CONFIRM_OTP_FAILURE: 'CONFIRM_OTP_FAILURE',
  LOGOUT: 'LOGOUT',
  SET_AUTH_TOKEN:'SET_AUTH_TOKEN'
};

function login(credentials) {
  return {
    type: ACTION_TYPES.LOGIN_REQUEST,
    credentials,
  };
}

function logout() {
  return {
    type: ACTION_TYPES.LOGOUT,
  };
}

function forgotPassword(params) {
  return {
    type: ACTION_TYPES.FORGOT_PASSWORD_REQUEST,
    params,
  };
}

function recoverPassword(params) {
  return {
    type: ACTION_TYPES.RECOVER_PASSWORD_REQUEST,
    params,
  };
}
function updatePassword(params) {
  return {
    type: ACTION_TYPES.PASSWORD_UPDATE_REQUEST,
    params,
  };
}

function register(params) {
  return {
    type: ACTION_TYPES.REGISTER_REQUEST,
    params,
  };
}


function confirmOTP(params) {
  return {
    type: ACTION_TYPES.CONFIRM_OTP_REQUEST,
    params,
  };
}

export const ACTIONS = {
  login,
  register,
  logout,
  recoverPassword,
  forgotPassword,
  updatePassword,
  confirmOTP
};
