export const ACTION_TYPES = {
  FETCH_TRUCK_MAKES_MODELS_REQUEST: '@truck/FETCH_TRUCK_MAKES_MODELS_REQUEST',
  FETCH_TRUCK_MAKES_MODELS_SUCCESS: '@truck/FETCH_TRUCK_MAKES_MODELS_SUCCESS',
  FETCH_TRUCK_MAKES_MODELS_FAILURE: '@truck/FETCH_TRUCK_MAKES_MODELS_FAILURE',

  FETCH_MY_TRUCK_REQUEST: '@truck/FETCH_MY_TRUCK_REQUEST',
  FETCH_MY_TRUCK_SUCCESS: '@truck/FETCH_MY_TRUCK_SUCCESS',
  FETCH_MY_TRUCK_FAILURE: '@truck/FETCH_MY_TRUCK_FAILURE',

  SAVE_TRUCK_REQUEST: '@truck/SAVE_TRUCK_REQUEST',
  SAVE_TRUCK_SUCCESS: '@truck/SAVE_TRUCK_SUCCESS',
  SAVE_TRUCK_FAILURE: '@truck/SAVE_TRUCK_FAILURE',

};

function fetchTruckMakesModels() {
  return {
    type: ACTION_TYPES.FETCH_TRUCK_MAKES_MODELS_REQUEST,
  };
}

function fetchMyTruck() {
  return {
    type: ACTION_TYPES.FETCH_MY_TRUCK_REQUEST,
  };
}

function saveTruck(params) {
  return {
    type: ACTION_TYPES.SAVE_TRUCK_REQUEST,
    params
  };
}

export const ACTIONS = {
  fetchTruckMakesModels,
  fetchMyTruck,
  saveTruck
};
